model:
  model_id: 'us.anthropic.claude-3-5-sonnet-20241022-v2:0'
  temperature: 0.0
  max_tokens: 8000
agent:
  devops-code-remediation-agent:
    name: DevOps Code Remediation
    type: bedrock
    order: 1
    instructions: |
      ## Instructions
      Provide the giturl and branch of the repository to be scanned. This agent will scan the repository and provide the results.
  name-lookup:
    model:
      temperature: 0.0
      max_tokens: 100
    name: Name Lookup
    type: mcp
    order: 5
    enable_memory: true
    instructions: |
      ## Instructions
      Provide the name of the person to lookup. This agent will provide the results.
      If the available tools does not solve the query, then use bedrock to get the answer.
      
      ## Sample Prompts
      - What is the phone number of <<name>>?
        - Example: "What is the phone number of John Doe?"
      - What is the email address of <<name>>?
        - Example: "What is the email address of Jane Smith?"
      - What is the address of <<name>>?
        - Example: "What is the address of Bob Johnson?"
    servers: [
      {
        'name': 'name_lookup_server',
        'command': 'python3.11',
        'args': [ 'mcp_servers/name_lookup_server.py' ],
        'description': 'This server provides name lookup tools',
        'title': 'Name Lookup Server'
      },
      {
        'name': 'scan_result',
        'command': 'python3.11',
        'args': [ 'mcp_servers/scan_results.py' ],
        'description': 'This server provides security scanning and analysis tools',
        'title': 'Scan Result Server'
      }
    ]
    system_prompt: |
      You are a helpful assistant with access to name lookup and repository result scan. 
      If necessary tools are not available, use model to get the answer. If the result is not available, inform the user that you are unable to find the information.
      Always provide clear responses.
  deployment-release-manager-agent:
    name: Deployment Release Manager
    type: mcp
    order: 2
    instructions: |
      ## Instructions
      Analyze the code scan result of the provided project and summarize the results. Based on that analysis, provide a list of recommended actions 
      and also indicate whether the project is ready for deployment or not.
      
      User can select from following level of report:
        - Summary Report
        - Detailed Report

    servers: [
      {
        'name': 'scan_result_server',
        'command': 'python3.11',
        'args': [ 'mcp_servers/scan_results.py' ],
        'description': 'This server provides security scanning and analysis tools',
        'title': 'Scan Result Server'
      },
      {
        'name': 'git_utils',
        'command': 'python3.11',
        'args': [ 'mcp_servers/git_server.py' ],
        'description': 'Git cloning and git operation tools',
        'title': 'Git Utils Server'
      }
    ]
    system_prompt: |
      You are a helpful assistant with access to code scan result tool. 
      Analyze the code scan result of the provided project and summarize the results. If the prompt already has the scan results, use those results directly.
      Based on that analysis, provide a list of recommended actions 
      and also indicate whether the project is ready for deployment or not.
  git-ops-agent:
    name: Git Ops
    type: mcp
    order: 3
    instructions: |
      ## Instructions
      Provide the giturl and the agent will clone the repository and can provide the following statistics:
        - commit history
        - file list
        - programming language used
        - repository structure
        - contributors stats
      
      User can select the list of statistics from the advanced options. By default, all statistics are provided.

    servers: [
      {
        'name': 'git_utils',
        'command': 'python3.11',
        'args': [ 'mcp_servers/git_server.py' ],
        'description': 'Git cloning and git operation tools',
        'title': 'Git Utils Server'
      }
    ]
    system_prompt: |
      You are a helpful assistant with access to git utilities. Format the output in a way that is easy to read and understand.
      Always provide clear responses.
  devops-lookup-agent:
    model:
      model_id: 'us.anthropic.claude-3-5-sonnet-20241022-v2:0'
      temperature: 0.0
      max_tokens: 8000
    name: DevOpsGPT
    type: mcp
    order: 4
    instructions: |
      ## Instructions
      This agent can answer general questions and provide information on a wide range of devops and software engineering topics.
    system_prompt: |
      You are a helpful assistant who can answer general questions and provide information on a wide range of devops and software engineering topics.
      Keep the topics relevant to devops and software engineering. Do  not provide information on topics that are not relevant to devops and software engineering.
      Always provide clear responses.
